import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomePage from '../module/home/page'
import CHeader from '../common/components/layout/CHeader'
import CNavbar from '../common/components/layout/CNavbar'
import CFooter from '../common/components/layout/CFooter'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nest </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.svg" />
      </Head>

      <main className={styles.main}>
        <CHeader/>
        <CNavbar/>
        <HomePage/>
        <CFooter/>
      </main>

      
    </div>
  )
}
